sudo: required
services:
  - docker

before_install:
  - docker build -t stevewangrui/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stevewangrui/react-test npm test

after_success:
  - docker build -t stevewangrui/multi-client ./client
  - docker build -t stevewangrui/multi-nginx ./nginx
  - docker build -t stevewangrui/multi-server ./server
  - docker build -t stevewangrui/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stevewangrui/multi-client
  - docker push stevewangrui/multi-nginx
  - docker push stevewangrui/multi-server
  - docker push stevewangrui/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-471112899833"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY