sudo: required
services:
  - docker

before_install:
  - docker build -t stevewangrui/react-test -f Dockerfile.dev ./client

script:
  - docker run -e CI=true stevewangrui/react-test npm test

after_success:
  - docker build -t stevewangrui/multi-client ./client
  - docker build -t stevewangrui/multi-nginx ./nginx
  - docker build -t stevewangrui/multi-server ./server
  - docker build -t stevewangrui/multi-worker ./worker